apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-test
  namespace: hipster-shop
spec:
  containers:
  - name: stress
    image: progrium/stress
    args: ["--cpu", "2", "--timeout", "300s"]
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 200m
  restartPolicy: Never
