apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: hipster-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: main
        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.10.0
        env:
        - name: FRONTEND_ADDR
          value: "frontend:8080"
        - name: USERS
          value: "10"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
