apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hipster-shop

resources:
- namespace.yaml
- frontend.yaml
- productcatalogservice.yaml
- cartservice.yaml
- currencyservice.yaml
- paymentservice.yaml
- shippingservice.yaml
- emailservice.yaml
- checkoutservice.yaml
- recommendationservice.yaml
- adservice.yaml

images:
- name: gcr.io/google-samples/microservices-demo/frontend
  newTag: v0.10.0
- name: gcr.io/google-samples/microservices-demo/productcatalogservice
  newTag: v0.10.0
- name: gcr.io/google-samples/microservices-demo/cartservice
  newTag: v0.10.0
- name: gcr.io/google-samples/microservices-demo/currencyservice
  newTag: v0.10.0
- name: gcr.io/google-samples/microservices-demo/paymentservice
  newTag: v0.10.0
- name: gcr.io/google-samples/microservices-demo/shippingservice
  newTag: v0.10.0
- name: gcr.io/google-samples/microservices-demo/emailservice
  newTag: v0.10.0
- name: gcr.io/google-samples/microservices-demo/checkoutservice
  newTag: v0.10.0
- name: gcr.io/google-samples/microservices-demo/recommendationservice
  newTag: v0.10.0
- name: gcr.io/google-samples/microservices-demo/adservice
  newTag: v0.10.0
