apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hipster-shop

resources:
- frontend.yaml
- cartservice.yaml
- productcatalogservice.yaml
- currencyservice.yaml
- paymentservice.yaml
- shippingservice.yaml
- emailservice.yaml
- checkoutservice.yaml
- recommendationservice.yaml
- loadgenerator.yaml

commonLabels:
  app.kubernetes.io/name: hipster-shop
  app.kubernetes.io/version: v0.10.0
  managed-by: argocd
