global:
  imageTag: "v0.10.0"
  imageRegistry: "gcr.io/google-samples/microservices-demo"

namespace: hipster-shop

services:
  frontend:
    image: "frontend"
    port: 8080
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
  productcatalogservice:
    image: "productcatalogservice"
    port: 3550
    replicas: 1
    
  cartservice:
    image: "cartservice"
    port: 7070
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 300m
        memory: 256Mi
    
  currencyservice:
    image: "currencyservice"
    port: 7000
    replicas: 1
    
  paymentservice:
    image: "paymentservice"
    port: 50051
    replicas: 1
    
  shippingservice:
    image: "shippingservice"
    port: 50051
    replicas: 1
    
  emailservice:
    image: "emailservice"
    port: 8080
    replicas: 1
    
  checkoutservice:
    image: "checkoutservice"
    port: 5050
    replicas: 1
    
  recommendationservice:
    image: "recommendationservice"
    port: 8080
    replicas: 1
    
  adservice:
    image: "adservice"
    port: 9555
    replicas: 1

loadbalancer:
  enabled: false
  type: ClusterIP
