apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipster-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbdurRehman924/hipster-shop.git
    targetRevision: main
    path: gitops/base/hipster-shop
  destination:
    server: https://kubernetes.default.svc
    namespace: hipster-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
