apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: hipster-shop
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - hipster-shop
    labelSelectors:
      app: productcatalogservice
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "0ms"
  duration: "2m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition
  namespace: hipster-shop
spec:
  action: partition
  mode: one
  selector:
    namespaces:
      - hipster-shop
    labelSelectors:
      app: recommendationservice
  direction: to
  target:
    mode: one
    selector:
      namespaces:
        - hipster-shop
      labelSelectors:
        app: productcatalogservice
  duration: "1m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: packet-loss
  namespace: hipster-shop
spec:
  action: loss
  mode: one
  selector:
    namespaces:
      - hipster-shop
    labelSelectors:
      app: checkoutservice
  loss:
    loss: "25"
    correlation: "100"
  duration: "1m"
