apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hipster-shop

resources:
- ../../base/hipster-shop

patchesStrategicMerge:
- frontend-patch.yaml

commonLabels:
  environment: dev

replicas:
- name: frontend
  count: 1
- name: cartservice
  count: 1
